### ISSUE TITLE
xvs.py source/url?

### ISSUE THREAD

**Issue by theChaosCoder** [emako/qvs#1]
Is xvs.py made by you or have you found it somewhere? I would like to add it to VSDB https://forum.doom9.org/showthread.php?t=175702

**Comment by theChaosCoder** [comment]
Oh and avsfunc.py :)

**Comment by emako** [comment]
xvs.py made by 78dalao, whom github homepage is https://github.com/xyx98
78dalao replied that it would be uploaded to github in 3 days.

**Comment by emako** [comment]
Check https://github.com/xyx98/my-vapoursynth-script

**Comment by theChaosCoder** [comment]
thx
