### ISSUE TITLE
VapourSynth-Editor r19 not support vapoursynth R57

### ISSUE THREAD

**Issue by YohoYang** [emako/qvs#5]
In the qvs r17 version, vapoursynth has been upgraded to R57, but the official version of VapourSynth-Editor r19 does not support preview, and the preview will display "Error forming pixmap from frame. Expected format CompatBGR32. Instead got 'YUV420P8'".
When replace the VapourSynth-Editor with r19-mod-5 and it will work fine. Can you consider updating the Editor to [https://github.com/YomikoR/VapourSynth-Editor](url)

Another, sometimes audio cut is needed, if it can directly provide built-in support, such as adding a cut file to the audio processing.

Thanks for the GUI.

**Comment by emako** [comment]
1. Fetching vsedit updates forward using r19-mod-5.
2. Audio tracks cutter is exactly useful at TVRip.
---
问题反馈群号：699742830

**Comment by emako** [comment]
> In the qvs r17 version, vapoursynth has been upgraded to R57, but the official version of VapourSynth-Editor r19 does not support preview, and the preview will display "Error forming pixmap from frame. Expected format CompatBGR32. Instead got 'YUV420P8'". When replace the VapourSynth-Editor with r19-mod-5 and it will work fine. Can you consider updating the Editor to [https://github.com/YomikoR/VapourSynth-Editor](url)
> 
> Another, sometimes audio cut is needed, if it can directly provide built-in support, such as adding a cut file to the audio processing.
> 
> Thanks for the GUI.

r19-mod-5 included after [r17.2](https://github.com/emako/qvs/releases/tag/r17.2) released.
